---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "Ansible-testRG"
        location: "eastus"
      register : rg
    - debug:
        var: rg